language: groovy
dist: trusty
jdk:
- openjdk8
- openjdk11
env:
  global:
  - TERM=dumb
  - MALLOC_ARENA_MAX=1
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=372m -XX:+CMSClassUnloadingEnabled"
  - secure: AhSoJSCqqVc+RxipbokWUCqaq+IMwrf61aoEh3EA9prKF0vy72J2uFfuDYBNI8ywKTSHkCQAqbQOdjbzMByzF9fqt74Glux9sjALiaPyyLpc/dKFA1CiII1IMAjL41cVS2cfdIfh1/j39+jevYEpmJQ6Me1JtG1NFRJZ+kxZSKFYNndnkM0KgLBnXH9sC3WdHz7XpG3iAgKXNsQlLqmBAHA95/nojIxC0uR3rHm2rwGTSooCe2VM0QNkpZobzU/yTG73N212dP8MkKCVr6PBHCYydXzJNP4/aTXmT8gZhEmh2BZZ52r3WoE995QnyOLkSM9pVMlkubLT/+C3B/g+I9tKuCIwCfnFXDJj0bMndsGs1QVVSf34z+i8YghX09yVjxRGQeBxX8VOm9IyguLM7Wy1aCaMBI3v4951QKvsmvqoCpvEjap2ZdnDfkqVeQ6A77vm+zhPsUyFqy7v+8PBV8dWMN3jP8kJ2MIhYUZGfCXzwvJH0hfoDUqd+AI2rPPkGD3ax8eJc+z6z4eQILRBDqCrFjpPLR8iAWur/qhUzZlOe3gFBLq0rip+lyxZeK0nSZACjs1dz4ikViWoH9oO9UPHsEo2VDLCF+IDhYWWHvw2oq/pCeaQ4G1AGIGiPOg13+slCK6qK2fdoV3bKw1LWuP6PCFWtdmHopcpmtwCPag=
  - secure: fQp8VyCszMV7FakVHqeoxvq3pv4rBax/NHnQeJ0zrEKkRKXRY3ouhFlZN3qan/SBG7vIK9AU0FC3C9Yo6xyubAd1PfLwS4rwtm1D/+R7Qjmvw19axoGGAW4oHmEoZK268pr0FWNO8JJpgE0QScicaG39iT0ccYupm/cAu/jYQKhPFM6DaTKe5Yw8PfE0mXRQg0ZGvCASTBGiZtF2nOUPOLrq0C53CccbxnSuQEm1Fvnpzsdtw7MnRYXHUkE5jfpl1lyXhbujtjRzKRVmsSbZfvaBij/SrwbgPcbqMMqsP/+8smz4VOkbJfVStgK1+rKRwakeqqakzGBxc1DQ1Mj4eDPUiAhZgZz+TisRc79UoQ08YXv+HaR5JTEM5UAW4zFb6JMemHY3Xdv9MPC9LYA8AUPX0xeeH29goliVvparqblZCcW66/W302tTqswy6Gn9JEg00MChx013dHABKLEk+OsUVQkaHr+6DJJnVpX75eHsJCZqlgxaRSGGHZlKyB26icUhrOaanvOnqeW2t4NeJOVPMsKLktE+aQqJu96rQYbcs1Zo0ASjQhcH3kl5/SB55B7ckFoBwuUcpJ+R5OB4s9wHCUbVny+NPhmuw9mqG4pDn2DXHUTlkiuLNh1q4w+ghXl6TDqC5zwkvxGDVUrjE00vR7kBQ3qjjzBoNesfdyk=
  - secure: A8jxxM1HP3hgQTEMjo+HkZ6KdRNrXiFB8cBkhAdoA1dhdyR6XM6p2mtVXWOyfhbi0N4YMdd2K68p4O9A2W8CY6mfacZ4syWCZnStE3djBqdfiA8cmgdiQCW13DfO4Cuq1JVXLJSybj6cgnjJD33W5qW9yjiQpW3DfH+P2pU2ugNajeLzubs5FvOjGIth7Jz4+hDP35r8f8pdaJPYSUTdswtRlbPvXND1HToZM7Vzmtk1OiLHqXk1GxIJsoqPY6iS4WQiSEc30l+ZMy9BTCWXTfU8hFfNQ82A/KRIKchGoveoNOWky0FXzSpTrIFlGHy0bjU0tBijk3NXLQH1i82GOpdFPqemTge2ck20mwLcmFMGs5x1WZI4ITzwT1SqliB7x3LSmMFQjmEQeTH/vgj7KbBC2nNyBf1+n8DU1MhEib99FpJVFOBnoukbhqpZX2dpkk7nOlAM9GhpYDL2vw2VNZarNu0TlSQIHJtPRTjmUZ6MBrZWZU+Kwzb2JdHUyDLWqPurLKBywmQaNEn67Fa8Q0Va8JjIYxlRgLyWVPHPx3LD5CUd5+wlKQ8OEBxtpA8oPa9giN6Qe7mHKOZZA402LTiUANdQeZzaUDPW52tA7zQrp8Wx/dWjQAH3gWoJP3p64FloSf4S88cQiDyGYWzUgvKzc54s6bSsjPEsCC2S+5Q=
before_install:
- ./travis/before-install.sh
script: "./travis/build.sh"
deploy:
  provider: pages:git
  on:
    all_branch: true
  before_deploy:
    - "./travis/prepare-docs.sh"
  token:
    secure: CR3sgRbZGiCQCDZOV6eLSr+9w7dO0qvSVsKfkHwOXS3MmH/IjwiAQHlq0YTgP2k/vEGywzZEWR0HoR4YnquvUdTPbPmCnjnQlFZC7/IlSqemh/6QQ7GakrF+kmTQDg/EoRNkmj3cNbpiwaG/YJrvawIok55cmfiiaZCB9vPAiXkANC6rF44oF4v7Jgt4vK9xZxbOOhMQnCp1D7s2h7T2v+/sokY78jsCtkRMngYGyyisQekXGEOT9aorplscZ9xuaD6wpG0ACEXlmumTlnGBF5XShTw56GRGcRl5d5qp9oWux28JtgdmavMJSqBCLtmgzB+EMKp+2G2eNqB7aKWyoDuZ7O0jO+m57UBEPOyLrH0qAm22wxnqI4bgDLaZwqsIw0BX+rbzVyr8lBN33wvlvz346MZNYO1CBX21Dgr+eZ6nNNg0vI3FdU1O2a4T42nCygleFp7hsWtC6GXwmG9vTZpz55W7Xeka82BfpETowx/ieJ059cE8M0Z6QLO+/EctQj+2zaZiKSTtJfME34GJtXO8fPpMCf74NRa2qKjFAzAb5sPi+kaXfGIzSKc/x7AcGecVr+sG+KwEl1bG9APjiqWSGtgZeQfvGpMeMT1keGWZuUYRiWrEsFGxfGMr5fsHo0Q5NNiHtGU2WZ+1CZiBg/a5/keQcnkQI52PW7cQu7A=
  edge: true
  verbose: true
  committer_from_gh: true

